# -*- coding: utf-8 -*-
"""bima pertemuan 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UCsx2QiDv8kK8pTpwaC6_pCn0eFe74G
"""

#1
kendaraan = ['beat karbu', 'motor', '200 cc', 'pink', 2]
kendaraan.append('13jt')
kendaraan.append('matic')
kendaraan.insert(2,'honda')
print(kendaraan)
print(kendaraan[0])
print(kendaraan[1])
print(kendaraan[2])
print(kendaraan[3])
print(kendaraan[4])

#2
hitung_luas=int(input("""pilih salah satu :
1.hitung luas persegi
2.hitung luas lingkaran
3.hitung luas segitiga"""))

match hitung_luas:
  case 1:
    print("menghitung luas persegi")
    sisi=int(input("masukan sisi : "))
    hitung_luas=sisi**2
    print("luas persegi adalah", hitung_luas)
  case 2:
    print("menghitung luas lingkaran")
    jari_jari=int(input("masukan jari-jari : "))
    hitung_luas=3.14*jari_jari**2
    print("luas lingkaran adalah", hitung_luas)
  case 3:
    print("menghitung luas segitiga")
    alas=int(input("masukan alas : "))
    tinggi=int(input("masukan tinggi : "))
    hitung_luas=alas*tinggi/2
    print("luas segitiga adalah", hitung_luas)
  case _:
    print("pilihan tidak ada")

